version: "3.3"

volumes:
  ore-db:
  uploads:

services:
  db:
    environment:
      POSTGRES_USER: oredb
      POSTGRES_PASSWORD: oredb
      POSTGRES_DB: oredb
    build:
      context: .
      dockerfile: pgDockerfile
    volumes:
      - ore-db:/var/lib/postgresql
    networks:
      - web
  app:
    build: .
    ports:
      - "9000:9000"
    stdin_open: true
    environment:
      BASE_URL: "http://localhost:9000"
      APPLICATION_SECRET: "secretkey"
      ORE_DEBUG: "false"
      ORE_STAGE: "false"
      JDBC_DATABASE_URL: "jdbc:postgresql://db/oredb"
      JDBC_DATABASE_USERNAME: "oredb"
      JDBC_DATABASE_PASSWORD: "oredb"
      ORE_AUTH_URL: "http://localhost:8000"
      ORE_AUTH_API_KEY: "changeme"
      ORE_AUTH_SSO_SECRET: "changeme"
      ORE_AUTH_SSO_API_KEY: "changeme"
    depends_on:
      - "db"
    volumes:
      - uploads:/home/ore/prod/uploads
    networks:
      - web
networks:
  web:
