- type: java\.time\.LocalDateTime
  specAsParameter:
    - type: string
      format: date-time
- type: java\.time\.OffsetDateTime
  specAsParameter:
    - type: string
      format: date-time
- type: ore\.permission\.NamedPermission
  specAsParameter:
    - $ref: '#/components/schemas/NamedPermission'
- type: NamedPermission
  specAsParameter:
    - $ref: '#/components/schemas/NamedPermission'
- type: ore\.data\.project\.Category
  specAsParameter:
    - $ref: '#/components/schemas/Category'
- type: Category
  specAsParameter:
    - $ref: '#/components/schemas/Category'
- type: ore\.models\.project\.Visibility
  specAsParameter:
    - $ref: '#/components/schemas/Visibility'
- type: ore\.models\.project\.ReviewState
  specAsParameter:
    - $ref: '#/components/schemas/ReviewState'
- type: controllers\.apiv2\.ApiV2Controller\.APIScopeType
  specAsParameter:
    - $ref: '#/components/schemas/ApiScopeType'
- type: controllers\.apiv2\.Authentication\.SessionType
  specAsParameter:
    - $ref: '#/components/schemas/SessionType'
- type: ProjectSortingStrategy
  specAsParameter:
    - $ref: '#/components/schemas/ProjectSortingStrategy'
- type: ore\.models\.project\.version\.stability
  specAsParameter:
    - $ref: '#/components/schemas/Stability'
- type: version\.stability
  specAsParameter:
    - $ref: '#/components/schemas/Stability'
- type: ore\.models\.project\.version\.releasetype
  specAsParameter:
    - $ref: '#/components/schemas/ReleaseType'
- type: version\.releasetype
  specAsParameter:
    - $ref: '#/components/schemas/ReleaseType'
- type: ore\.permission\.role\.role
  specAsParameter:
    - $ref: '#/components/schemas/Role'
- type: controllers\.apiv2\.Users\.UserSortingStrategy
  specAsParameter:
    - $ref: '#/components/schemas/UserSortingStrategy'